# Generated by Django 5.1 on 2024-09-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('produitId', models.AutoField(primary_key=True, serialize=False)),
                ('produitname', models.CharField(max_length=100)),
                ('photoName', models.CharField(max_length=500)),
            ],
        ),
    ]
