# Generated by Django 5.1.1 on 2024-09-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_expedition', models.TextField()),
                ('date_commentaire', models.DateTimeField()),
                ('statut', models.CharField(max_length=100)),
                ('commentaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produit.user')),
            ],
        ),
    ]
