# Generated by Django 5.1.1 on 2024-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='panier',
            name='date_creation_commande',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
