# Generated by Django 5.1.1 on 2024-09-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_remove_panier_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_amount',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='commande',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.user'),
        ),
    ]
