# Generated by Django 5.1.1 on 2024-09-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_category_updated_at_commande_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
