version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Davide2020@@
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis : 
    image: "redis:alpine"

  celery:
    build: 
    command: ["celery", "-A", "mon_projet_ecommerce", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  

  web:
    build: .
    command:  ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
